
version: 2

sources:
  - name: 'model1'
    description: 'Person Details'
    database: 'sanity'
    schema: 'PUBLIC'
    tables:
     - name: 'sanity_tb2_02_w_pk'
       description: 'details of a person'
       columns:
        - name: company_id
          description: 'unique id of person'
          tests:
            - unique
            - not_null 
            
  - name: 'model2'
    description: 'size greater than 0'
    database: 'sanity'
    schema: 'PUBLIC'
    tables:
     - name: 'sanity_tb2_02_w_pk'
       description: 'details of a person'
       columns:
        - name: company_id
          description: 'id of person'
          tests:
            - not_null

  - name: 'model3'
    description: 'monthly spend is greater than 0'
    database: 'sanity'
    schema: 'PUBLIC'
    tables:
     - name: 'sanity_tb2_02_w_pk'
       description: 'details of a person'
       columns:
        - name: company_id
          description: 'id of person'
          tests:
            - not_null
