
version: 2

sources:
  - name: 'model1'
    description: 'Person Details'
    database: 'pg_dataprofile_04'
    schema: 'public'
    tables:
     - name: 'tbl_05_postgres_profile'
       description: 'details of a person'
       columns:
        - name: id
          description: 'unique id of person'
          tests:
            - unique
            - not_null 
            
  - name: 'model2'
    description: 'age greater than 40'
    database: 'pg_dataprofile_04'
    schema: 'public'
    tables:
     - name: 'tbl_05_postgres_profile'
       description: 'phoneno of a person with id'
       columns:
        - name: id
          description: 'id of person'
          tests:
            - not_null

  - name: 'model3'
    description: 'age greater than 75'
    database: 'pg_dataprofile_04'
    schema: 'public'
    tables:
     - name: 'tbl_05_postgres_profile'
       description: 'phoneno of a person with id'
       columns:
        - name: id
          description: 'id of person'
          tests:
            - not_null
