
version: 2

sources:
  - name: 'model1'
    description: 'Person Details'
    database: 'sanity'
    schema: 'PUBLIC'
    tables:
     - name: 'dummy_table_which_does_not_exist_1'
       description: 'details of a person'
       columns:
        - name: id
          description: 'unique id of person'
          tests:
            - unique
            - not_null 
            
  - name: 'model2'
    description: 'Person Phone no'
    database: 'sanity'
    schema: 'PUBLIC'
    tables:
     - name: 'dummy_table_which_does_not_exist_2'
       description: 'phoneno of a person with id'
       columns:
        - name: id
          description: 'id of person'
          tests:
            - not_null 
